#For the VM
services :
  mysql_db:
    image: mysql:8.0.45
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_cz
    restart: always
    environment:
      MYSQL_DATABASE: cesizen
      MYSQL_ROOT_PASSWORD: exampleRootPwd
      MYSQL_USER: exampleUsr
      MYSQL_PASSWORD: examplePwd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uexampleUsr", "-pexamplePwd"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    image: ghcr.io/elodieguyard/cesizen:release
    container_name: cesizen_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      mysql_db:
        condition: service_healthy
  wud:
    image: getwud/wud
    container_name: wud
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mysql_data:

