package com.example.cesizen.controller;

import com.example.cesizen.model.User;
import com.example.cesizen.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

//Based on https://spring.io/guides/gs/accessing-data-mysql
@RestController // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class UserController {

        @Autowired // This means to get the bean called userRepository
        // Which is auto-generated by Spring, we will use it to handle the data
        private UserRepository userRepository;

        @PostMapping(path="/add") // Map ONLY POST Requests
        public @ResponseBody String addNewUser (@RequestParam String name,
                                                @RequestParam String email) { //TODO à modifier
            // @ResponseBody means the returned String is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request

            User n = new User();
            n.setName(name);
            userRepository.save(n);
            return "Saved";
        }

        @GetMapping(path="/all")
        public Iterable<User> getAllUsers() {
            // This returns a JSON or XML with the users
            return userRepository.findAll();
        }

        @GetMapping(path="/{id}")
        public User getUser(@PathVariable Integer id) {
            return userRepository.findById(id).get();
        }

        @PutMapping(path="/update")
        public @ResponseBody String updateUser(@RequestParam Integer Id, @RequestParam String name){
            return "Updated";
        }

        @DeleteMapping(path="/delete")
        public @ResponseBody String deleteById(@RequestParam Integer Id){
            userRepository.deleteById(Id);
            return "Deleted"; // return http status 200 ?
        }
    }
