package com.example.cesizen.controller;

import com.example.cesizen.model.Role;
import com.example.cesizen.model.User;
import com.example.cesizen.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.web.bind.annotation.*;

import java.util.Date;

//Based on https://spring.io/guides/gs/accessing-data-mysql
@RestController // This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /demo (after Application path)
public class UserApiController {

        @Autowired // This means to get the bean called userRepository
        // Which is auto-generated by Spring, we will use it to handle the data
        private UserRepository userRepository;

        @PostMapping(path="/add") // TODO : Attention au cyptage côté front mobile, a dev, corriger cette méthode en conséquence
        public @ResponseBody String addNewUser (@RequestBody User user) {
            // @ResponseBody means the returned String is the response, not a view name

            user.setRole(Role.USER); // mettre le role user par défaut
            BCryptPasswordEncoder BCryptPasswordEncoder = new BCryptPasswordEncoder(); //instancie l'encoder
            user.setMot_de_passe(BCryptPasswordEncoder.encode(user.getMot_de_passe())); // encrypte le mdp saisi par l'user
            //TODO : Injection par Autowire passwordEncoder = bonne pratique
            // :!\ le mdp ici transit en clair du device vers le serveur spring avant encodage !!!!
            user.setEnabled();
            userRepository.save(user); // persisteren db
            return "Saved";
        }

        @GetMapping(path="/all")
        public Iterable<User> getAllUsers() {
            // This returns a JSON or XML with the users
            return userRepository.findAll();
        }

        @GetMapping(path="/{id}")
        public User getUser(@PathVariable Long id) {
            return userRepository.findById(id).get();
        }

        //TODO changer en RequestBody plutôt
        @PutMapping(path="/update") // modifie seulement le nom de l'utilisateur et met à jour la date de modification
        public @ResponseBody String updateUser(@RequestParam Long Id, @RequestParam String name){
            userRepository.findById(Id).ifPresent(u -> {
                u.setName(name);
                u.setModifie_le(new Date());
                userRepository.save(u);
            });

            return "Updated";
        }

        @DeleteMapping(path="/delete")
        public @ResponseBody String deleteById(@RequestParam Long Id){
            userRepository.deleteById(Id);
            return "Deleted"; // return http status 200 ?
        }
    }
