name: CI - Build / Security / Quality / Docker
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest
    steps:
      #Récupère le code source du repo dans le runner pour build à partir de l'action checkout pour docker build
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven local repository
        uses: actions/cache@v4 # Mis en cache des dépendances Maven pour build plus rapidement et réduire le trafic réseau
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build (skip tests temporairement le temps de les développer)
        run: mvn -B clean package

      - name: Depcheck #OWASP Dependency Check : démarche DevSecOps pour identifier les CVE et surveillances des dépendances tierces
        uses: dependency-check/Dependency-Check_Action@main
        continue-on-error: false
        env:
          # actions/setup-java@v1 changes JAVA_HOME so it needs to be reset to match the depcheck image
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'CesiZen Backend'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
            --disableCentral
        # L’analyse OWASP s’appuie sur plusieurs sources. Maven Central peut parfois être indisponible ou limiter les requêtes dans les environnements CI.
        #Ce n’est pas bloquant car les principales bases de vulnérabilités (NVD) restent utilisées

      - name: Upload Dependency Check report
        uses: actions/upload-artifact@v4
        if: always()  # Important : uploade même si le job échoue
        with:
          name: Depcheck report
          path: reports/dependency-check-report.html

        # Display Dependency Check Results (optionnel)
      - name: Display Dependency Check Results
        if: always()
        run: cat reports/dependency-check-report.html | grep -oP 'vulnerability.*?</td>' || echo "Report generated"

      # Upload des résultats de tests
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: surefire-test-report
          path: target/surefire-reports/

      - name: Upload artifact (jar)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  sonar: # Couvre la qualité du code, la dette technique, les bugs potentiels, la sécurité
    name: Build and analyze
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 21
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: 21
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarQube packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ElodieGuyard_CeziZen
      # ça rebuild ici, mais dans ce contexte de dev, ça remonte des informations pertinentes

  docker-build: # industrialisation, reproductibilité du déploiement
    name: Build Docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag cesizen:latest